Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-05, with the labels that each got.

#58 hotfix: openai version lock
  package.json
Labels: size:XS, lgtm

#65 chore: add package lock changes for openai dependency change
  package-lock.json
Labels: size:XS

#53 Prompt Render Response
  src/apis/generations.ts
Labels: size:M, lgtm

#55 update feedback
  src/apiResource.ts
  src/apis/feedback.ts
  src/baseClient.ts
Labels: size:S, lgtm

#63 Prevent from dropping customHost headers
  src/_types/generalTypes.ts
  src/baseClient.ts
  src/client.ts
Labels: size:XS, lgtm

#66 1.3.0
  package-lock.json
  package.json
Labels: size:XS
