Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-09, with the labels that each got.

#102 Add huggingface_base_url parameter support autocompletions for x-p…
  src/_types/generalTypes.ts
  src/baseClient.ts
  src/client.ts
Labels: size:XS, lgtm

#104 fix: Type response in PortkeyClient because of issues with inferred type
  src/client.ts
Labels: size:XS, lgtm

#96 Remove unused locals (to fix Typescript noUnusedLocals problem)
  src/baseClient.ts
  src/streaming.ts
Labels: size:XS, lgtm

#99 Vertex Changes
  src/_types/generalTypes.ts
  src/apis/chatCompletions.ts
  src/baseClient.ts
  src/client.ts
Labels: size:S

#101 Feat/oai4.55.3
  package-lock.json
  package.json
  src/_types/portkeyConstructs.ts
  src/apis/assistants.ts
  src/apis/audio.ts
  src/apis/batches.ts
  src/apis/betaChat.ts
  src/apis/chatCompletions.ts
  src/apis/completions.ts
  src/apis/files.ts
  src/apis/fineTuning.ts
  src/apis/index.ts
  src/apis/moderations.ts
  src/apis/threads.ts
  src/apis/uploads.ts
  src/apis/vectorStores.ts
  src/client.ts
  src/utils.ts
  tests/audio/openai.test.ts
  tests/audio/speech.mp3
  tests/moderations/openai.test.ts
Labels: size:XXL

#106 1.4.0-rc.1
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS

#107 Update SECURITY.md
  SECURITY.md
Labels: size:XS, lgtm

#112 Fix/unused variable
  src/apis/betaChat.ts
  src/apis/chatCompletions.ts
  src/apis/moderations.ts
  src/apis/uploads.ts
Labels: size:S, lgtm

#109 AnthropicBeta header
  src/_types/generalTypes.ts
  src/baseClient.ts
  src/client.ts
Labels: size:XS

#115 1.4.0
  package-lock.json
  package.json
  speech.mp3
  src/version.ts
Labels: size:XS
