Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-10, with the labels that each got.

#88 Users, Invites, Workspaces and Members API
  src/apiResource.ts
  src/apis/admin.ts
  src/apis/index.ts
  src/baseClient.ts
  src/client.ts
  src/utils.ts
Labels: size:XL, lgtm

#120 Configs API Added
  src/apis/configs.ts
  src/apis/index.ts
  src/client.ts
  src/utils.ts
Labels: size:L, lgtm

#122 Feat/api keys
  src/apis/apiKeys.ts
  src/apis/index.ts
  src/client.ts
  src/utils.ts
Labels: size:L, lgtm

#126 Virtual Keys API
  src/apis/index.ts
  src/apis/virtualKeys.ts
  src/client.ts
  src/utils.ts
Labels: size:L, lgtm

#124 Request and Response Type
  src/_types/portkeyConstructs.ts
  src/apis/assistants.ts
  src/apis/embeddings.ts
  src/apis/files.ts
  src/apis/images.ts
  src/apis/moderations.ts
  src/apis/threads.ts
  src/apis/uploads.ts
  src/apis/vectorStores.ts
Labels: size:M, lgtm

#127 1.5.0
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS, lgtm

#114 Linting + Prettier
  .eslintrc.js
  .prettierrc.json
  package.json
  src/_types/generalTypes.ts
  src/_types/portkeyConstructs.ts
  src/apiResource.ts
  src/apis/admin.ts
  src/apis/apiKeys.ts
  src/apis/assistants.ts
  src/apis/audio.ts
  src/apis/batches.ts
  src/apis/betaChat.ts
  src/apis/chatCompletions.ts
  src/apis/completions.ts
  src/apis/configs.ts
  src/apis/createHeaders.ts
  src/apis/embeddings.ts
  src/apis/feedback.ts
  src/apis/files.ts
  src/apis/fineTuning.ts
  src/apis/generations.ts
  src/apis/images.ts
  src/apis/index.ts
  src/apis/models.ts
  src/apis/moderations.ts
  src/apis/postMethod.ts
  src/apis/threads.ts
  src/apis/uploads.ts
  src/apis/vectorStores.ts
  src/apis/virtualKeys.ts
  src/baseClient.ts
  src/client.ts
  src/constants.ts
  src/error.ts
  src/index.ts
  src/streaming.ts
  src/utils.ts
  src/version.ts
Labels: size:XXL, lgtm
