Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-11, with the labels that each got.

#136 feat: Logs Export API
  src/apis/index.ts
  src/apis/logsExport.ts
  src/client.ts
  src/utils.ts
Labels: size:L, lgtm

#133 Spread Operator Issue: #130
  src/baseClient.ts
Labels: size:XS, lgtm

#137 1.5.2
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS, lgtm

#132 Making API Key optional is self hosted gateway
  src/client.ts
  src/constants.ts
  src/error.ts
  src/utils.ts
Labels: size:M, lgtm

#139 1.5.3
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS, lgtm

#142 feat: create and run stream support
  src/apis/threads.ts
  src/baseClient.ts
  src/utils.ts
Labels: size:M, lgtm

#143 1.5.4
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS, lgtm
