Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-03, with the labels that each got.

#40 Feat/wrapper
  package-lock.json
  package.json
  src/apis/assistants.ts
  src/apis/chatCompletions.ts
  src/apis/completions.ts
  src/apis/embeddings.ts
  src/apis/files.ts
  src/apis/images.ts
  src/apis/index.ts
  src/apis/models.ts
  src/apis/threads.ts
  src/baseClient.ts
  src/client.ts
  src/constants.ts
  src/utils.ts
  tests/assistants/openai.test.ts
  tests/chat/anthropic.test.ts
  tests/chat/anyscale.test.ts
  tests/chat/openai.test.ts
  tests/completion/anthropic.test.ts
  tests/completion/anyscale.test.ts
  tests/completion/openai.test.ts
  tests/images/image.png
  tests/images/imageMask.png
  tests/images/openai.test.ts
Labels: size:XXL, lgtm

#46 Feat/release 1.2.0
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS

#45 Feat/render
  src/apis/generations.ts
Labels: size:S, lgtm

#48 Feat/release 1.2.1
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS

#49 Add OpenAI SDK compliant blurb to readme
  README.md
Labels: size:XS, lgtm
