Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-02, with the labels that each got.

#30 Feat/new embeddings params
  src/apis/embeddings.ts
Labels: size:XS

#31 1.1.4
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS

#34 fix: cacheForceRefresh and empty headers fix
  src/_types/generalTypes.ts
  src/apis/createHeaders.ts
  src/baseClient.ts
  src/client.ts
Labels: size:S, lgtm

#35 1.1.5
  package-lock.json
  package.json
Labels: size:XS

#37 Update README.md
  README.md
Labels: size:L, lgtm
