Repository Portkey-AI/portkey-node-sdk, pull requests merged in 2024-07, with the labels that each got.

#92 response_format
  src/apis/chatCompletions.ts
Labels: size:XS

#89 fix: initializer for apiKey and baseURL
  src/client.ts
Labels: size:XS

#81 vercel response
  src/apis/chatCompletions.ts
Labels: size:S

#72 improvement: Tests for newer models of anyscale and openai
  jest.config.ts
  tests/chat/anyscale.test.ts
  tests/chat/openai.test.ts
Labels: size:M

#93 1.3.2
  package-lock.json
  package.json
  src/version.ts
Labels: size:XS

#95 Client Initialization + Max retries
  src/apis/assistants.ts
  src/apis/files.ts
  src/apis/images.ts
  src/apis/models.ts
  src/apis/threads.ts
  src/utils.ts
Labels: size:L
